name: CMake

on:
  workflow_call:

permissions: {}

jobs:
  cmake:
    strategy:
      matrix:
        include:
        - name: macOS
          os: macos-latest
          cmake_preset: macos-xcode
    name: CMake (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: |
        cmake --preset ${{ matrix.cmake_preset }}
    - name: Build
      run: |
        cmake --build --preset ${{ matrix.cmake_preset }}
    - name: Install
      run: |
        sudo cmake --install build
  cmake-windows:
    name: CMake (Windows SDL2)
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Update vcpkg
      run: |
        cd "$VCPKG_INSTALLATION_ROOT"
        git.exe pull origin master
        bootstrap-vcpkg.bat
    - name: Prepare vcpkg cache
      uses: actions/cache@v4
      with:
        path: ~/AppData/Local/vcpkg/archives
        key: cmake-vcpkg-cache-${{ github.sha }}
        restore-keys: |
          cmake-vcpkg-cache-
    - name: Install dependencies
      run: |
        vcpkg.exe --triplet x64-windows install sdl2 sdl2-mixer sdl2-image zlib
    - name: Build
      run: |
        cmake.exe -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DENABLE_IMAGE=ON \
                           -DENABLE_TOOLS=ON -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT\\scripts\\buildsystems\\vcpkg.cmake" \
                           -DVCPKG_TARGET_TRIPLET=x64-windows
        cmake.exe --build build --config Debug
    - name: Install
      run: |
        cmake.exe --install build --config Debug
