name: CMake

on:
  workflow_call:

permissions: {}

jobs:
  cmake:
    strategy:
      matrix:
        include:
        - name: macOS
          os: macos-latest
          cmake_preset: macos-xcode
        - name: win32
          os: windows-2025
          cmake_preset: macos-xcode
    name: CMake (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build Number
      run: |
        TMP_JOB_ID="$GITHUB_RUN_ID"
        TMP_BRANCH=$(basename ${GITHUB_REF#refs/heads/})
        TMP_PR_ID="$PULL_REQUEST"
        TMP_COMMIT=$(git rev-parse --short "$GITHUB_SHA")

        echo "BUILD_NUMBER=${TMP_JOB_ID}-${TMP_BRANCH}-${TMP_PR_ID}-${TMP_COMMIT}" >> $GITHUB_ENV
    - name: Configure
      run: |
        cmake --preset ${{ matrix.cmake_preset }}
    - name: Build
      run: |
        cmake --build --preset ${{ matrix.cmake_preset }}
