name: Code style check

on:
  workflow_call:

permissions: {}

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Setup clang-format
        run: |
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-17 100
          sudo update-alternatives --install /usr/bin/clang-format-diff clang-format-diff /usr/bin/clang-format-diff-17 100
      - name: Check code format
        run: |
          bash tools/builder/check_code_format.sh
